version: '3.9'

networks:
  my_network:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: test_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=fran
      - RABBITMQ_DEFAULT_PASS=cinha
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my_network


  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: consumer_service
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - 8082:8082
    networks:
      - my_network


  publisher:
    build:
      context: ./publisher
      dockerfile: Dockerfile
    container_name: publisher_service
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - my_network
