version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: test_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=fran
      - RABBITMQ_DEFAULT_PASS=cinha