version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: test_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=fran
      - RABBITMQ_DEFAULT_PASS=cinha

# disclaimer: usei o docker compose para subir o container do RabbitMQ & pensando em subir os containers do pub e do consumer, (os outros containers viraram to-do)